"""Small, privacy-preserving helpers for the Hermes media companion.

The extension package deliberately keeps policy-file and log handling separate
from any HTTP, Telegram, or process-management code.  The public exports are
the typed primitives used by those higher-level layers.
"""

from .whitelist_helper import (
    ALLOWLIST_VARIABLE,
    DEFAULT_MAX_LOG_BYTES,
    DEFAULT_MAX_LOG_LINE_BYTES,
    DEFAULT_MAX_LOG_RECORDS,
    MAX_POLICY_FILE_BYTES,
    AdminRemovalDenied,
    AllowlistError,
    AllowlistParseError,
    AllowlistSnapshot,
    BlockedUserEvent,
    FingerprintMismatch,
    LogInputError,
    MutationResult,
    PolicyFileError,
    PolicyParseError,
    SymlinkRejected,
    add_allowed_user,
    allowlist_fingerprint,
    extract_blocked_user_event,
    mutate_allowlist,
    parse_allowed_users,
    parse_blocked_gateway_logs,
    parse_blocked_log,
    parse_blocked_logs,
    parse_blocked_user_log,
    parse_blocked_user_logs,
    parse_whitelist,
    read_allowlist,
    read_telegram_allowlist,
    remove_allowed_user,
    semantic_fingerprint,
    StaleFingerprintError,
)

__all__ = [
    "ALLOWLIST_VARIABLE",
    "DEFAULT_MAX_LOG_BYTES",
    "DEFAULT_MAX_LOG_LINE_BYTES",
    "DEFAULT_MAX_LOG_RECORDS",
    "MAX_POLICY_FILE_BYTES",
    "AdminRemovalDenied",
    "AllowlistError",
    "AllowlistParseError",
    "AllowlistSnapshot",
    "BlockedUserEvent",
    "FingerprintMismatch",
    "LogInputError",
    "MutationResult",
    "PolicyFileError",
    "PolicyParseError",
    "SymlinkRejected",
    "add_allowed_user",
    "allowlist_fingerprint",
    "extract_blocked_user_event",
    "mutate_allowlist",
    "parse_allowed_users",
    "parse_blocked_gateway_logs",
    "parse_blocked_log",
    "parse_blocked_logs",
    "parse_blocked_user_log",
    "parse_blocked_user_logs",
    "parse_whitelist",
    "read_allowlist",
    "read_telegram_allowlist",
    "remove_allowed_user",
    "semantic_fingerprint",
    "StaleFingerprintError",
]
